import {catalog,solarLesson,solarQuest} from './content.js';
import {getModule} from './modules.js';
const app=document.querySelector('#app');
const state={grade:'grade_p4',subject:null};
function shell(content,mode='KidLearn'){app.innerHTML=`<main class="shell"><header class="header"><div class="brand">KidLearn Interactive</div><span class="mode">${mode}</span></header>${content}</main>`}
function home(){shell(`<section class="hero"><div class="icon">✨</div><h1>เรียนให้สนุก เข้าใจให้จริง</h1><p>เลือกโหมดที่ต้องการ เรียนรู้เปิดได้ทันที ส่วนการประเมินจะยืนยันตัวตนก่อนบันทึกคะแนน</p></section><section class="grid"><button class="card" data-learn><div class="icon">🚀</div><h2>เรียนรู้</h2><p class="muted">สำรวจบทเรียนและกิจกรรมได้โดยไม่ต้องล็อกอิน</p><strong>เริ่มเรียน →</strong></button><button class="card" data-assess><div class="icon">🎯</div><h2>ประเมินความเข้าใจ</h2><p class="muted">ยืนยันตัวตนก่อนเริ่ม และบันทึกคะแนนเมื่อส่งสำเร็จ</p><strong>เข้าสู่การประเมิน →</strong></button></section>`);app.querySelector('[data-learn]').onclick=browse;app.querySelector('[data-assess]').onclick=assessmentPlaceholder}
function browse(){const subjects=catalog.subjects.filter(x=>x.gradeId===state.grade);shell(`<div class="crumb"><button class="secondary" data-home>← หน้าแรก</button></div><section class="hero"><h1>เลือกสิ่งที่อยากเรียน</h1><p>เริ่มจากระดับชั้น แล้วเลือกวิชา</p></section><div class="actions">${catalog.grades.map(g=>`<button class="${g.id===state.grade?'primary':'secondary'}" data-grade="${g.id}">${g.name}</button>`).join('')}</div><h2>วิชา</h2><section class="grid">${subjects.map(s=>`<button class="card" data-subject="${s.id}"><div class="icon">${s.icon}</div><h3>${s.name}</h3><p class="muted">${s.description}</p></button>`).join('')}</section>`,'เรียนรู้');app.querySelector('[data-home]').onclick=home;app.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>{state.grade=b.dataset.grade;browse()});app.querySelectorAll('[data-subject]').forEach(b=>b.onclick=()=>{state.subject=b.dataset.subject;lesson()})}
function lesson(){if(state.subject!=='science-p4'){shell(`<button class="secondary" data-back>← กลับ</button><div class="card"><h2>เนื้อหากำลังเตรียม</h2><p>Phase 1 เปิดใช้กิจกรรมต้นแบบวิทยาศาสตร์ ป.4 ก่อน เพื่อทดสอบสถาปัตยกรรม Hub</p></div>`,'เรียนรู้');app.querySelector('[data-back]').onclick=browse;return}shell(`<button class="secondary" data-back>← วิทยาศาสตร์ ป.4</button><section class="hero"><div class="icon">🪐</div><h1>${solarLesson.title}</h1><p>${solarLesson.summary}</p></section><div class="card"><h2>เราจะเรียนรู้อะไร</h2><ul>${solarLesson.objectives.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="card mission" style="margin-top:16px"><span class="pill">LearnQuest</span><h2>${solarQuest.title}</h2><p>${solarQuest.instructions}</p><p class="muted">กิจกรรม: สำรวจ • เลือกคำตอบ • จับคู่ • เรียงลำดับ</p><button class="primary" data-start>เริ่มภารกิจ</button></div>`,'เรียนรู้');app.querySelector('[data-back]').onclick=browse;app.querySelector('[data-start]').onclick=quest}
function quest(){shell(`<div class="header"><button class="secondary" data-exit>× ออกจากภารกิจ</button></div><section id="quest-host"></section>`,'LearnQuest');app.querySelector('[data-exit]').onclick=lesson;getModule('learnquest').mount(app.querySelector('#quest-host'),solarQuest,{mode:'learn',onComplete:lesson})}
function assessmentPlaceholder(){shell(`<button class="secondary" data-home>← หน้าแรก</button><section class="hero"><div class="icon">🎯</div><h1>ประเมินความเข้าใจ</h1><p>Phase 1 แสดงโครง UX ก่อน ส่วนการค้นหาผู้เรียนและบันทึกคะแนนจริงจะเชื่อม Apps Script ใน Phase 2</p></section><div class="card"><label for="learner"><strong>รหัสผู้เรียน</strong></label><input id="learner" disabled placeholder="เชื่อม Backend ใน Phase 2" style="width:100%;margin-top:10px;min-height:52px;padding:12px;border:1px solid var(--border);border-radius:14px"><div class="actions"><button class="primary" disabled>ค้นหา</button></div></div>`,'ประเมิน');app.querySelector('[data-home]').onclick=home}
home();
